"""Django settings for the Lancer Advancer project."""
import os
import time
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Identifies this running server build. Changes on every (re)start so clients can
# detect a deploy and reload. Honour an explicit build id or Fly's machine
# version when present; otherwise fall back to the process start time.
BUILD_ID = (
    os.environ.get("BUILD_ID")
    or os.environ.get("FLY_MACHINE_VERSION")
    or str(int(time.time()))
)

# How often (seconds) each WebSocket pings the client with the current build id.
HEARTBEAT_SECONDS = 15


def _env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: str) -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "dev-insecure-key-change-me-in-production"
)

DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1],testserver"
)

CSRF_TRUSTED_ORIGINS = _env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "http://localhost:8080,http://127.0.0.1:8080",
)

INSTALLED_APPS = [
    "daphne",  # must precede staticfiles so runserver uses the ASGI stack
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "channels",
    "game",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        # Single-instance, in-memory layer. No Redis. The deployment MUST run
        # exactly one process for game state and the channel layer to stay
        # consistent between the two players.
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# In production use WhiteNoise's hashed + compressed manifest storage (the
# manifest is generated by `collectstatic` at image build time). In DEBUG use
# plain storage so templates render without a prebuilt manifest.
_staticfiles_backend = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": _staticfiles_backend,
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security headers are relaxed in DEBUG; tightened automatically when DEBUG is
# off (i.e. in the Fly.io deployment) so traffic is forced over HTTPS/WSS.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = False  # Fly handles TLS termination + redirect
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
